const meals = [
    {name:"Mandazi", img:"images/mandazi.png", ingredients:["2 cups flour","1/2 cup sugar","1 tsp baking powder","1/4 tsp salt","1/2 cup coconut milk","Oil"], steps:["Combine dry ingredients.","Knead with coconut milk.","Rest for 30 mins.","Fry until golden brown."]},
    {name:"Chapati", img:"images/chapati.jpg", ingredients:["2 cups flour","1/2 tsp salt","1/2 cup water","2 tbsp oil"], steps:["Mix flour/salt.","Knead with water.","Rest 30 mins.","Roll thin and cook on skillet."]},
    {name:"Fried Cassava", img:"images/fried cassava.jpg", ingredients:["500g cassava","Salt","Oil"], steps:["Peel and cut cassava.","Boil until soft.","Fry until golden."]},
    {name:"Pan Cakes", img:"images/pancakes.png", ingredients:["1 cup flour","2 tbsp sugar","1 tsp baking powder","1 cup milk","1 egg","Vanilla"], steps:["Mix dry ingredients.","Whisk wet ingredients.","Combine and cook on skillet."]},
    {name:"Samosas", img:"images/samosa.jpg", ingredients:["2 cups flour","Salt","Water","Filling","Oil"], steps:["Make dough.","Prepare filling.","Fold cones, fill and seal.","Deep fry."]},
    {name:"Boiled Eggs", img:"images/eggs.jpg", ingredients:["Eggs","Water","Salt"], steps:["Boil eggs for 8-10 mins.","Cool and peel."]},
    {name:"Black Tea", img:"images/tea.webp", ingredients:["2 cups water","1 tsp tea leaves","Sugar"], steps:["Boil water with tea.","Simmer and strain."]},
    {name:"Toasted Bread", img:"images/Bread.jpg", ingredients:["Bread slices","Butter"], steps:["Heat pan.","Toast until golden.","Spread butter."]},
    {name:"Vegetable Samosa (A pair)", img:"images/vegetable.jpg", ingredients:["Samosa pastry","Veggie filling","Oil"], steps:["Fill pastry.","Fold and seal.","Fry until crisp."]},
    {name:"Beef Samosa(A pair)", img:"images/beef.png", ingredients:["Samosa pastry","Minced beef","Oil"], steps:["Cook beef filling.","Fold into pastry.","Fry until hot and golden."]},
    {name:"Mandazi (A pair)", img:"images/mandazi.jpg", ingredients:["Dough from recipe"], steps:["Shape discs.","Fry in hot oil."]},
    {name:"Beef Pie", img:"images/beef pie.jpg", ingredients:["Pie crust","Minced beef","Oil"], steps:["Prepare filling.","Fill crust and seal.","Bake or fry."]},
    {name:"Cookies", img:"images/cookies.webp", ingredients:["2 cups flour","1 cup sugar","1/2 cup butter","Vanilla","1 egg"], steps:["Cream butter/sugar.","Add egg/flour.","Bake at 180°C for 12 mins."]},
    {name:"Home fries", img:"images/fries.jpg", ingredients:["Potatoes","Oil","Spices"], steps:["Cube potatoes.","Parboil.","Fry until golden."]},
    {name:"Baked Beans", img:"images/beans.jpg", ingredients:["Canned beans","Onions","Tomato paste"], steps:["Sauté onions.","Add beans/paste.","Simmer 10 mins."]},
    {name:"Egg Rolls (A pair)", img:"images/egg rolls.jpg", ingredients:["Pastry","Filling","Oil"], steps:["Roll filling in pastry.","Seal edges.","Deep fry."]},
    {name:"American Pancake", img:"images/american.jpg", ingredients:["1 cup flour","Sugar","Baking powder","1 egg","3/4 cup milk"], steps:["Form batter.","Cook until bubbles form.","Flip and serve."]},
    {name:"Kikomando", img:"images/kikomando.jpg", ingredients:["Chapati","Beans","Spices"], steps:["Cut chapati.","Prepare beans.","Mix together."]},
    {name:"Fried Rice", img:"images/rice.webp", ingredients:["Rice","Veggies","Oil","Soy sauce"], steps:["Cook rice.","Stir fry veggies.","Mix with soy sauce."]},
    {name:"Matooke", img:"images/matooke.jpg", ingredients:["Matooke","Salt","Water"], steps:["Peel and mash.","Steam until soft."]},
    {name:"White Rice & Beans", img:"images/white rice.jpg", ingredients:["Rice","Beans","Salt"], steps:["Cook separately.","Serve together."]},
    {name:"Anyoya", img:"images/anyoya.jpeg", ingredients:["Maize flour","Water","Salt"], steps:["Mix flour/water.","Cook until firm."]},
    {name:"Chicken/Liver/Goat/Beef Stew", img:"images/chicken stew.jpg", ingredients:["Meat","Onions","Tomatoes","Spices"], steps:["Brown meat.","Add tomatoes/spices.","Simmer until tender."]},
    {name:"Cold Water", img:"images/nivana.jpg", ingredients:["Bottled water"], steps:["Serve chilled."]},
    {name:"Fresh Juice", img:"images/juice.jpg", ingredients:["Fruits","Water","Sugar"], steps:["Blend fruits.","Strain and chill."]},
    {name:"Cold sodas", img:"images/soda.jpg", ingredients:["Carbonated water","Flavor"], steps:["Pour over ice."]},
    {name:"Bongo", img:"images/bongo.jpg", ingredients:["Ingredients"], steps:["Serve over ice."]},
    {name:"Guiness", img:"images/guiness.jpg", ingredients:["Guinness"], steps:["Pour carefully."]},
    {name:"Bond 7", img:"images/bond7.jpg", ingredients:["Bond 7"], steps:["Serve chilled."]},
    {name:"Smirnoff", img:"images/smirnoff.jpg", ingredients:["Smirnoff"], steps:["Serve or mix."]},
    {name:"Club Pilsener", img:"images/club.jpg", ingredients:["Pilsner"], steps:["Serve chilled."]},
    {name:"Minute maid", img:"images/maid.jpg", ingredients:["Juice"], steps:["Pour chilled."]},
    {name:"Bushera", img:"images/bushera.jpg", ingredients:["Millet flour","Water","Sugar"], steps:["Mix and boil until thick."]},
    {name:"Oner", img:"images/oner.jpg", ingredients:["Oner"], steps:["Serve chilled."]},
    {name:"Yorghurt", img:"images/yogurt.jpg", ingredients:["Milk","Culture"], steps:["Ferment and chill."]}
  ];
